/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ChainLinkMATICUSDPriceFeed,
  ChainLinkMATICUSDPriceFeedInterface,
} from "../ChainLinkMATICUSDPriceFeed";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "answeredInRound",
        type: "uint80",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50609f8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063feaf968c14602d575b600080fd5b604080516802000000000015d36c8082526308ef744f60208301526361fbcf4b8284018190526060830152608082015290519081900360a00190f3fea26469706673582212207fe55bd51a37d425be7b078db7800c262c9c5e6544eae6c337227b8ef521ab4264736f6c63430008040033";

export class ChainLinkMATICUSDPriceFeed__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ChainLinkMATICUSDPriceFeed> {
    return super.deploy(overrides || {}) as Promise<ChainLinkMATICUSDPriceFeed>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChainLinkMATICUSDPriceFeed {
    return super.attach(address) as ChainLinkMATICUSDPriceFeed;
  }
  connect(signer: Signer): ChainLinkMATICUSDPriceFeed__factory {
    return super.connect(signer) as ChainLinkMATICUSDPriceFeed__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChainLinkMATICUSDPriceFeedInterface {
    return new utils.Interface(_abi) as ChainLinkMATICUSDPriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainLinkMATICUSDPriceFeed {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ChainLinkMATICUSDPriceFeed;
  }
}
