/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ChainLinkETHUSDPriceFeed,
  ChainLinkETHUSDPriceFeedInterface,
} from "../ChainLinkETHUSDPriceFeed";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "answeredInRound",
        type: "uint80",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060a08061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063feaf968c14602d575b600080fd5b6040805168020000000000162047808252643c7da9fb6560208301526361fbcf038284018190526060830152608082015290519081900360a00190f3fea26469706673582212202b474c11618538d2b478ee9ec23f264c3fd21a28df00edf09eda22e78e47428a64736f6c63430008040033";

export class ChainLinkETHUSDPriceFeed__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ChainLinkETHUSDPriceFeed> {
    return super.deploy(overrides || {}) as Promise<ChainLinkETHUSDPriceFeed>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChainLinkETHUSDPriceFeed {
    return super.attach(address) as ChainLinkETHUSDPriceFeed;
  }
  connect(signer: Signer): ChainLinkETHUSDPriceFeed__factory {
    return super.connect(signer) as ChainLinkETHUSDPriceFeed__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChainLinkETHUSDPriceFeedInterface {
    return new utils.Interface(_abi) as ChainLinkETHUSDPriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainLinkETHUSDPriceFeed {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ChainLinkETHUSDPriceFeed;
  }
}
